-- 部門テーブル Oracle標準のサンプルテーブル
CREATE TABLE DEPT
(
    DEPTNO NUMBER(2) NOT NULL PRIMARY KEY,
    DNAME  VARCHAR2(14),
    LOC    VARCHAR2(13)
);

COMMENT ON COLUMN DEPT.DEPTNO IS '部門No';
COMMENT ON COLUMN DEPT.DNAME IS '部門名';
COMMENT ON COLUMN DEPT.LOC IS '部門の場所';