-- 社員テーブル Oracle標準のサンプルテーブル
CREATE TABLE EMP
(
    EMPNO    NUMBER(4) NOT NULL PRIMARY KEY,
    ENAME    VARCHAR2(10),
    JOB      VARCHAR2(9),
    MGR      NUMBER(4),
    HIREDATE DATE,
    SAL      NUMBER(7, 2),
    COMM     NUMBER(7, 2),
    DEPTNO   NUMBER(2)

);

COMMENT ON COLUMN EMP.EMPNO IS '従業員コード';
COMMENT ON COLUMN EMP.ENAME IS '従業員名';
COMMENT ON COLUMN EMP.JOB IS '職種';
COMMENT ON COLUMN EMP.MGR IS '上司の従業員コード';
COMMENT ON COLUMN EMP.HIREDATE IS '採用日';
COMMENT ON COLUMN EMP.SAL IS '給料';
COMMENT ON COLUMN EMP.COMM IS '年俸';
COMMENT ON COLUMN EMP.DEPTNO IS '部門番号';